name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # or your preferred Node.js version

      - name: Install Dependencies
        run: npm install
        working-directory: ./gesture_play  # Adjust if necessary

      - name: Run ESLint
        run: npx eslint .
        working-directory: ./gesture_play  # Adjust if necessary

      - name: Upload ESLint report
        uses: actions/upload-artifact@v3
        with:
          name: eslint-report
          path: ./gesture_play/eslint_report.txt # Adjust if you generate a report file
