name: CI

on: push

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout error
        uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.7'
      - name: Install Dependencies
        run: pip install -r tests/requirements.txt
      
      - name: Run Tests
        run: | 
          cd tests
          pytest -v
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Specify the version of Node.js you need

      - name: Install ESLint
        run: npm install eslint

      - name: Run ESLint
        run: npx eslint .
