name: CI

on: push

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout error
        uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.7'
      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-results/

      
      - name: Run Tests
        run: | 
          pytest -v
