name: CI

on: push

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.7'

      - name: Install Python Dependencies
        run: pip install -r requirements.txt
      
      # - name: Run Python Tests
      #   run: pytest -v

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Node.js Dependencies
        run: |
          npm install
          npm install -g jest

      - name: Run JavaScript Unit Tests
        run: jest

      - name: Run JavaScript Browser Tests
        run: |
          google-chrome --version
          google-chrome --headless --disable-gpu --remote-debugging-port=9222 --disable-dev-shm-usage --no-sandbox tests.html