name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # or your preferred Node.js version

      - name: Install Dependencies
        working-directory: ./gesture_play # Update this to your actual path
        run: |
          npm install

      - name: Run ESLint
        working-directory: ./gesture_play # Update this to your actual path
        run: |
          npx eslint .
