name: CI

on: push

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # or your desired version
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm install
      
      - name: Fix ESLint permissions
        run: chmod +x ./node_modules/.bin/eslint
      
      - name: Run ESLint
        run: npx eslint .
