name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List directory contents
        run: |
          echo "Current directory:"
          pwd
          echo "Listing files:"
          ls -R  # List all files and directories recursively

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Change this if you need a different version

      - name: Install Dependencies
        run: |
          npm install

      - name: Run ESLint
        run: |
          npx eslint .

      - name: Run Tests
        run: |
          npm test  # Assuming you have a test script defined in package.json
