# .github/workflows/test.yml
name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    - name: Run tests
      run: |
        google-chrome --version
        google-chrome --headless --disable-gpu --remote-debugging-port=9222 --disable-dev-shm-usage --no-sandbox tests.html